name: Manually trigger an Azure Machine Learning job

on:
  workflow_dispatch:

jobs:
  train:
    runs-on: ubuntu-latest
    steps:
    
    # step 1
    - name: Check out repo
      uses: actions/checkout@main
      
    # step 2  
    - name: Install az ml extension
      run: az extension add -n ml -y
      
    # step 3
    - name: Azure login
      uses: azure/login@v1
      with:
        creds: ${{secrets.AZURE_CREDENTIALS}}

    # step 4
    - name: Run Azure ML Job from Challenge 1
      uses: az ml job create --file 
